"""add tier and billing fields to organisation

Revision ID: 271987996191
Revises: 0009
Create Date: 2026-04-11 17:51:45.473545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271987996191'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('tier', sa.String(length=20), nullable=False, server_default='free'))
    op.add_column('organisations', sa.Column('jobs_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('organisations', sa.Column('billing_period_start', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'billing_period_start')
    op.drop_column('organisations', 'jobs_this_month')
    op.drop_column('organisations', 'tier')
    # ### end Alembic commands ###
