"""add review_mode and tone to translation_job

Revision ID: 53c6ab2d28b9
Revises: e8b20e4cc910
Create Date: 2026-04-11 18:31:14.285217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c6ab2d28b9'
down_revision: Union[str, Sequence[str], None] = 'e8b20e4cc910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_jobs', sa.Column('review_mode', sa.String(length=20), nullable=False, server_default='autopilot'))
    op.add_column('translation_jobs', sa.Column('tone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_jobs', 'tone')
    op.drop_column('translation_jobs', 'review_mode')
    # ### end Alembic commands ###
