"""add source editing fields to document_block and translation_job

Revision ID: 6bb309eb1ea9
Revises: a868eb354352
Create Date: 2026-04-12 14:00:03.183904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb309eb1ea9'
down_revision: Union[str, Sequence[str], None] = 'a868eb354352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_blocks', sa.Column('source_edited', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('document_blocks', sa.Column('original_source_text', sa.Text(), nullable=True))
    op.add_column('translation_jobs', sa.Column('source_edit_word_delta', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_jobs', 'source_edit_word_delta')
    op.drop_column('document_blocks', 'original_source_text')
    op.drop_column('document_blocks', 'source_edited')
    # ### end Alembic commands ###
