"""add project model and project_id to document

Revision ID: e8b20e4cc910
Revises: 271987996191
Create Date: 2026-04-11 18:18:49.804065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b20e4cc910'
down_revision: Union[str, Sequence[str], None] = '271987996191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('tone_override', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_column('documents', 'tone_override')
    op.drop_column('documents', 'project_id')
    # ### end Alembic commands ###
